language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
    - $(npm config get prefix)/bin/grunt-cli
    - $(npm config get prefix)/bin/bower
node_js:
  - node # latest Node.js release
before_script:
  - npm list -g grunt-cli --depth=0 || npm install -g grunt-cli
  - npm list -g bower --depth=0 || npm install -g bower
  - bower install
  # used for Firefox and Chrome to work
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/webdriver-manager update
  - echo "CURRENT VERSIONS"
  - npm list
  - bower list
script:
  - npm run test-travis
addons:
  sauce_connect: true
